version: '3.8'

services:
  
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  database:
    image: adminer
    restart: always
    depends_on:
      - postgres
      - mongo
    ports:
      - '8080:8080'

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: cleanCodeDatabase
    volumes:
      - data-mongo:/data/db
      - mongo-seed.js:/docker-entrypoint-initdb.d/mongo-seed.js
    ports:
      - '27017:27017'

volumes:
  db_data:
  data-mongo:
  mongo-seed.js: