version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  database:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - '8080:8080'

 
volumes:
  db_data:
